config/routes.rb
QratrRails::Application.routes.draw do

  root to: 'playlists#last'

  resources :playlists, :only => [ :show ]
  get '/new', to: 'playlists#new'
  get '/playlists/:id/tracks/:track_id', to: 'playlists#show'

  get '/tracks/create.json', to: 'tracks#create'
  put '/tracks/:id', to: 'tracks#update'

  post '/subscriber', to: 'subscribers#create'

  resources :admin, :only => [ :index ] do
    put 'assign', on: :collection
  end

  post 'signup', to: 'users#create'
  resources :users, :only => [ :new, :create ]

  post 'login', to: 'sessions#create'
  resources :sessions, :only => [ :new, :create ]

  get 'logout', to: 'sessions#destroy'

  post '/favorites', to: 'favorites#create'
  delete '/favorites', to: 'favorites#destroy'
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :favorited_track, class_name: "Track"

  # validates_uniqueness_of :user_id, :scope => :favorited_track_id
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  has_many :tracks, -> { order(:duration) }

  def url
    ApplicationHelper::Url::root_domain + "/playlists/#{id}"
  end

  def prev_playlist_name
    Playlist.find(id - 1).name  if has_prev_playlist
  end

  def next_playlist_name
    Playlist.find(id + 1).name  if has_next_playlist
  end

  def has_prev_playlist
    id != Playlist.first.id
  end

  def has_next_playlist
    id != Playlist.last.id
  end

  # TODO - Test this method
  def as_json_with_tracks
    playlist_decorator = PlaylistDecorator.new(self)
    additional_data = {
      'url' => url,
      'prev_playlist_name' => prev_playlist_name,
      'next_playlist_name' => next_playlist_name,
      'has_prev_playlist' => has_prev_playlist,
      'has_next_playlist' => has_next_playlist,
      'total_duration' => playlist_decorator.total_duration,
      'tracks' => tracks.map(&:as_json_custom)
    }
    self.as_json.merge(additional_data)
  end
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  validates_uniqueness_of :email
  after_save :save_to_mailchimp

  def save_to_mailchimp
    gb = Gibbon::API.new(ENV["MAILCHIMP_API_KEY"])
    gb.lists.subscribe({
      :id => "3541caf364",
      :email => {
        :email => self.email
      },
      :double_optin => false
    })
  end
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :playlist

  has_many :favorites, foreign_key: "favorited_track_id"
  has_many :users, through: :favorites

  validates_uniqueness_of :permalink_url
  validates_presence_of :title, :artist, :permalink_url, :stream_url

  def as_json_custom
    track_decorator = TrackDecorator.new(self)
    additional_data = {
      'mix' => track_decorator.mix?
    }
    self.as_json.merge(additional_data)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :favorites
  has_many :favorited_tracks, through: :favorites, class_name: "Track"

  attr_accessor :password
  before_save :encrypt_password

  validates :email, :username, :password, presence: true
  validates :email, :username, uniqueness: true
  validates :password, length: { minimum: 6 }
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

  def as_json_with_favorites
    additional_data = {
      'favorites' => self.favorited_tracks
    }
    self.as_json.merge(additional_data)
  end

  def self.authenticate(email_or_username, password)
    user = User.find_by_email(email_or_username) || User.find_by_username(email_or_username)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @tracks = Track.where(:playlist_id => nil).order(:duration).map{ |track| TrackDecorator.new(track) }
  end

  def assign
    @playlist = Playlist.create(name: params[:playlist_name])
    params[:track_ids].each { |track_id| @playlist.tracks << Track.find(track_id) }
    redirect_to @playlist
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  rescue_from ActiveRecord::RecordNotFound do |exception|
    render 'public/404.html', :status => 404
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id])  if session[:user_id]
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = Favorite.new(favorite_params)
    if favorite.save
      render :json => favorite.to_json
    else
      render status: 401, nothing: true
    end
  end

  def destroy
    favorite = Favorite.find_by_user_id_and_favorited_track_id(params[:favorite][:user_id], params[:favorite][:favorited_track_id])
    favorite.destroy
    render :json => { success: true }
  end

  def favorite_params
    params.require(:favorite).permit(:user_id, :favorited_track_id)
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def index
    @playlists = Playlist.all
  end

  def show
    @playlist = Playlist.find(params[:id])
    @track = @playlist.tracks.find(params[:track_id])  if params[:track_id]
    respond_to do |format|
      format.html
      format.js { render :json => @playlist.as_json_with_tracks.to_json }
    end
  end

  def new
    @playlist = Playlist.new
  end

  def last
    @playlist = Playlist.last
    render "show"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      render :json => user.as_json_with_favorites.to_json
    else
      render status: 401, nothing: true
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  def create
    @subscriber = Subscriber.find_or_create_by_email(params[:email])
    respond_to do |format|
      format.js { render :json => {email: @subscriber.email}.to_json }
    end
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def create
    @track = TrackCreator.build(params[:url])
  end

  def update
    @track = Track.find(params[:id])
    @track.update_attribute(:play_count, params[:play_count])
    render :nothing => true
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      render :json => @user.as_json_with_favorites.to_json
    else
      render status: 401, nothing: true
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  class Url
    def self.root_domain
      ENV["ROOT_DOMAIN"] || "http://localhost:5000"
    end
  end
end

app/helpers/decorator.rb
module Decorator
  class Base
    attr_reader :model

    def initialize(model)
      @model = model
    end

    def method_missing(method, *args)
      @model.send(method, *args)
    end
  end
end

app/views/admin/index.haml
.admin

  %h1 Qratr - Admin Dashboard

  .backlog-tracks-container
    .section-title
      .title Backlog
      .hint All the tracks in DB that don't have a playlist_id.
    
    .backlog-tracks
      = form_tag assign_admin_index_path, :method => :put do |f|
        - @tracks.each do |track|
          .track-container{'data-track-id' => track.id}
            .artwork
              %img{:src => track.artwork_url}
            .metadata
              .artist= track.artist
              .title= track.title
            .track-id.right= check_box_tag "track_ids[]", track.id
        = text_field_tag :playlist_name
        .br
        = submit_tag "Submit"

app/views/admin/index.html.haml
.admin

  %h1 Qratr - Admin Dashboard

  .backlog-tracks-container
    .section-title
      .title Backlog
      .hint All tracks in DB that don't have a playlist_id.
      .hint Drag/drop them to the staging area on the right.

    .add-a-track
      %form
        %input{:name => "link", :placeholder => "Paste a Soundcloud Url"}
        %button{:title => "Add", :type => "submit"}
    
    .backlog-tracks
      - @tracks.each do |track|
        = partial(:track, :locals => {:track => track})

  .staged-tracks-container
    .section-title
      .title Staged for Publication
      .hint Reorder tracks and hit "Publish" to publish live.

    .staged-tracks

      .publish-container
        %button.publish-button{:title => "Publish", :type => "submit"}

app/views/layouts/application.haml
!!! 5
%head
  %link{:rel => "icon", :type => "image/png", :href =>"http://www.qratr.fm/assets/favicon.png"}
  %meta{:name => "viewport", :content =>"width=device-width"}
  %script{:src => "//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"}
  %script{:src => "//connect.soundcloud.com/sdk.js"}
  %link{:href => "//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css", :rel => "stylesheet"}
  = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
  = javascript_include_tag "application", "data-turbolinks-track" => true
  = javascript_include_tag "google_analytics"
  = csrf_meta_tags
  = yield :custom_head
  = yield :facebook_open_graph
  = render('partials/typekit')
  = render('partials/google_analytics')
  = render('partials/mixpanel')
  
%body
  = yield
  #fb-root
  = render('partials/facebook_sdk')

app/views/layouts/application.html.haml
!!! 5
%head
  = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
  = javascript_include_tag "application", "data-turbolinks-track" => true
  = csrf_meta_tags
  = yield :custom_head
%body
  = yield

app/views/partials/_facebook_sdk.haml
:javascript
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=1388716701376440";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

app/views/partials/_google_analytics.haml
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-47712756-1', 'qratr.fm');
  ga('send', 'pageview');

app/views/partials/_mixpanel.haml
- if Rails.env.production?
  :javascript
    (function(e,b){if(!b.__SV){var a,f,i,g;window.mixpanel=b;a=e.createElement("script");a.type="text/javascript";a.async=!0;a.src=("https:"===e.location.protocol?"https:":"http:")+'//cdn.mxpnl.com/libs/mixpanel-2.2.min.js';f=e.getElementsByTagName("script")[0];f.parentNode.insertBefore(a,f);b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!== typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.track_charge people.clear_charges people.delete_user".split(" ");for(g=0;g<i.length;g++)f(c,i[g]);
      b._i.push([a,e,d])};b.__SV=1.2}})(document,window.mixpanel||[]);
      mixpanel.init("103d386fae8578627751d9b9dc08562f");
- else
  :javascript
    window.mixpanel = {
      track: function() { }
    };

app/views/partials/_typekit.haml
%script{:type => "text/javascript", :src => "//use.typekit.net/byu8csc.js"}
:javascript
  try{Typekit.load();}catch(e){}

app/views/playlists/_footer.haml
.footer
  .container
    .center
      %span.brand Qratr.fm
      is a monthly curation of new music we're excited about.
      .social
        Follow us on
        %a.social-button.facebook-button{:href => "https://www.facebook.com/qratr", :target => "_blank"} Facebook
        and
        %a.social-button.twitter-button{:href => "https://twitter.com/qratr", :target => "_blank"} Twitter

    .left
      .important Keyboard Shortcuts
      %table
        %tbody
          %tr
            %td Space
            %td Play/Pause
          %tr
            %td ←
            %td Previous Playlist
          %tr
            %td →
            %td Next Playlist
          %tr
            %td ↑
            %td Previous Track
          %tr
            %td ↓
            %td Next Track
    .right
      .important.section-title Curators
      %ul.contributors
        %li
          .link= link_to "Guillaume Galuz", "http://gal.uz", :target => "_blank"
        %li
          .link= link_to "Benoit Destailleur", "https://www.facebook.com/benoit.destailleur", :target => "_blank"
        %li
          .link= link_to "Stephane Guinet", "https://twitter.com/Stephn_G", :target => "_blank"
        %li
          .link= link_to "Derek Opperman", "https://twitter.com/derekopperman", :target => "_blank"
        %li
          .link= link_to "Brandon Bussolini", "https://twitter.com/babussolini", :target => "_blank"

      .link.contact= mail_to 'guillaume.galuz@gmail.com', "Contact", :target => "_blank"

app/views/playlists/_head.haml
- content_for :custom_head do
  %title= "Qratr.fm"

- content_for :facebook_open_graph do
  - if @track
    %meta{:property => "og:image", :content => "#{@track.artwork_url}" }
    %meta{:property => "og:title", :content => "Qratr.fm | #{@track.artist} - #{@track.title}" }
    %meta{:property => "og:url", :content => "#{@track.permalink_url}" }
    %meta{:property => "og:type", :content => "website" }
  - else
    %meta{:property => "og:image", :content => "http://www.qratr.fm/assets/logo.png" }
    %meta{:property => "og:title", :content => "Qratr.fm - #{@playlist.name}" }
    %meta{:property => "og:url", :content => "#{@playlist.url}" }
    %meta{:property => "og:type", :content => "website" }

app/views/playlists/_header.haml
.header
  .container
    .header-left-container
      .logo
        Qratr.fm
    .header-right-container
      - if current_user
        .email #{current_user.email}
        .avatar
          %img{:src => avatar_url(current_user)}
      - else
        .user-links
          .login Login
          .separator •
          .signup Sign Up

app/views/playlists/_javascript.haml
:javascript
  SC.initialize({
    client_id: "7b0148ec311a1ffa34c7e0248ed2c9de",
  });

:javascript
  $(function() {
    mixpanel.track("Page View");
    if (#{Rails.env.development?}) {
      window.localStorage.clear();
    }

    window.playerState = new PlayerState();
    playerState.set('displayPlaylist', new Playlist(#{@playlist.as_json_with_tracks.to_json}));
    new PlaylistView({model: playerState.get('displayPlaylist')});
    new NavigationView();
    new Player();
    new PlayerMetadataView();
    new SharingButtonsView();
    new PlaybackButtonsView();
    new ProgressBarView();
    new PageTitleView();
    new KeyboardView();
    new HeaderView();
    new SubscribeView();
    new LoginModalView();
    new SignupModalView();

    var router = new Router();
    Backbone.history.start({pushState: true}); 
  });

app/views/playlists/_navigation.haml
.navigation
  .container
    .navigation-prev
      .navigation-icon.icon-prev-playlist
      .navigation-text.text-prev
    .navigation-next
      .navigation-icon.icon-next-playlist
      .navigation-text.text-next

app/views/playlists/_player.haml
.player
  .container
    .player-left-container
    .player-right-container
      .sharing-buttons
      .playback-buttons
  
    .progress-bar
      .elapsed

app/views/playlists/_subscribe.haml
.subscribe.container
  .email
    .subscribe-text Receive an email when we publish a new playlist.
    .subscribe-form
      %input{:name => "email", :placeholder => "brian.eno@googlemail.co.uk", :class => "subscribe-input", :type => "text"}
      %button{:class => "subscribe-button"} Subscribe
      %span{:class => "hide-button"} Hide

app/views/playlists/new.haml
:javascript
  $(function() {
    new CreatePlaylistView();
  });

.container
  %h1{:style => "text-align: center;"} Create a playlist
  .add-a-track
    %input{:name => "link", :placeholder => "Paste a Soundcloud or YouTube link"}
    .fetch-status
  .playlist-container

app/views/playlists/show.haml
= render('head')
= render('player')
.header
= render('subscribe')
.playlist-container.container
= render('navigation')
= render('footer')
= render('javascript')

app/views/playlists/show.html.haml
- content_for :custom_head do
  %title= "Qratr | #{@playlist.name}"

#player
  .container
    %ul
      %li.track-artist
      %li.track-title
      %li.soundcloud-logo
        %a{:href => "", :target => 'blank'}
          = image_tag("http://www.iconsdb.com/icons/preview/orange/soundcloud-xxl.png")

.container
  .logo
    = image_tag("logo.png")
    
.playlist-container.container
  .playlist-title= @playlist.name

  - @playlist.tracks.each do |track|
    .track-container{'data-track-id' => track.id}
      .artwork
        = image_tag(track.artwork_url)
      .metadata
        .title= track.title
        .artist= track.artist

.footer.container
  %a.prev{:href => prev_playlist_url(@playlist.id)} #{prev_playlist_name(@playlist.id)}
  %a.next{:href => next_playlist_url(@playlist.id)} #{next_playlist_name(@playlist.id)}

%script{:src => "//connect.soundcloud.com/sdk.js"}
:javascript
  SC.initialize({
    client_id: "7b0148ec311a1ffa34c7e0248ed2c9de",
  });
  $(function() {
    window.playlist = new Playlist(#{@playlist.as_json_with_tracks.to_json});
    new PlaylistView({model: playlist});
    window.player = new PlayerView();
  });

app/views/tracks/create.haml
.confirmation= "#{@track.artist} - #{@track.title} has been added!"

%a{:href => @track.permalink_url} Back to Soundcloud

app/views/users/new.haml
%h1 Sign Up

= form_for @user do |f|
  = f.email_field :email, :placeholder => "email"
  = f.password_field :password, :placeholder => "password"
  = f.submit "Signup"